# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Wallace Ecological Modeling App
email: wallaceEcoMod@gmail.com
author: Jamie M. Kass
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/wallaceEcoMod/wallace
  - title: email
    url: mailto:wallaceEcoMod@gmail.com
